name: Terraform Infrastructure Test
run-name: Terraform Test (${{ github.actor }})
on: [push]
env:
  PEM_FILENAME: swen_514_team3_key.pem
jobs:
  terraform-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .pem file from AWS_PEM_KEY secret
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > terraform/$PEM_FILENAME
          chmod 400 terraform/$PEM_FILENAME
        shell: bash

      - name: Create mock credentials
        run: |
          echo '
          
          provider "aws" {
            region                      = "${var.region}"
            skip_credentials_validation = true
            skip_requesting_account_id  = true
            skip_metadata_api_check     = true
            access_key                  = "${{ secrets.TF_PLAN_AWS_ACCESS_KEY }}"
            secret_key                  = "${{ secrets.TF_PLAN_AWS_SECRET_KEY }}"
          }
          
          ' >> terraform/aws_mock.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        if: success() || failure()
        run: cd terraform/ && terraform validate

      - name: Terraform Plan
        run: | 
          cd terraform/
          terraform plan -input=false -var "key_name=$PEM_FILENAME"
