name: Terraform Infrastructure Test
run-name: Terraform Test (${{ github.actor }})
on: [push]
env:
  PEM_FILENAME: swen_514_team3_key.pem
jobs:
  terraform-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .pem file from AWS_PEM_KEY secret
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > terraform/$PEM_FILENAME
          chmod 400 terraform/$PEM_FILENAME
        shell: bash

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        if: success() || failure()
        run: cd terraform/ && terraform validate

      - name: Terraform Plan
        run: | 
          cd terraform/
          terraform plan -input=false -var "key_name=$PEM_FILENAME"
