name: Terraform Infrastructure Test
run-name: Terraform Test (${{ github.actor }})
on: [push]
env:
  PEM_FILENAME: swen_514_team3_key.pem
jobs:
  terraform-test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    env:
      AWS_EC2_METADATA_DISABLED: ""
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Create .pem file from AWS_PEM_KEY secret
        run: |
          echo "${{ secrets.AWS_PEM_KEY }}" > terraform/${{ env.PEM_FILENAME }}
          chmod 400 terraform/${{ env.PEM_FILENAME }}
        shell: bash

      - name: Setup aws provider
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.TF_PLAN_AWS_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.TF_PLAN_AWS_SECRET_KEY }}
        shell: bash
        run: |
          echo 'provider "aws" {
            region = "${var.region}"
            access_key = "$AWS_ACCESS_KEY_ID"
            secret_key = "$AWS_SECRET_ACCESS_KEY"
          }' >> terraform/aws_mock.tf
          
          echo "---------------------------------------"
          echo "ACCESS KEY:  "
          echo ${{ secrets.TF_PLAN_AWS_ACCESS_KEY }} | sed 's/./& /g' 
          echo "---------------------------------------"
          cat terraform/aws_mock.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - run: terraform --version
      
      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        if: success() || failure()
        run: cd terraform/ && terraform validate

      - name: Terraform Plan
        run: | 
          cd terraform/
          terraform plan -input=false -var "key_name=${{ env.PEM_FILENAME }}"
        shell: bash
