name: Unit Tests
run-name: Running Unit Tests (${{ github.actor }})
on:
  push:
    branches:
      - '*'
jobs:
  # Terraform Tests
  terraform-test:
    name: Terraform Test
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup aws provider
        shell: bash
        run: |
          echo 'provider "aws" {
            region = "${var.region}"
            access_key = "${{ secrets.TF_PLAN_AWS_ACCESS_KEY }}"
            secret_key = "${{ secrets.TF_PLAN_AWS_SECRET_KEY }}"
          }
          variable "swen514_repo_fork" {
            description = "Input the github repo url to host the amplify app to (If you're a collaborator of the original repo then you need to create a fork and reference that)"
            default     = "https://github.com/jym2584/SWEN514-Team3"
          }
          
          variable "github_token" {
            description = "Input github token (classic) to deploy amplify app"
            default     = ""
          }
          
          ' >> terraform/aws_provider.tf

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - run: terraform --version
      
      - name: Terraform Init
        run: cd terraform/ && terraform init

      - name: Terraform Validate
        if: success() || failure()
        run: cd terraform/ && terraform validate

      - name: Terraform Plan
        run: | 
          cd terraform/
          terraform plan -input=false
        shell: bash
